---
title: 'A great vaccination experience'
author: "Kishore Puthezhath"
output:
  html_document:
    toc: true
    toc_float: true
date: '2021-01-23'
slug: COVID19 Vaccination
categories: Personal experience
tags: Life
subtitle: ''
summary: ''
authors: []
lastmod: ''
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
bibliography: mypub.bib
csl: vancouver.csl
link-citations: yes
---

Sharing a great vaccination experience





Since the announcement of vaccination program from Jan 16^th^ 2021, I felt amazement at the scientific accomplishment.


I understand that the AZD1222 (Covishield) vaccine is a replication-deficient simian adenovirus vector, containing the full‐length codon‐optimized coding sequence of SARS-CoV-2 spike protein along with a tissue plasminogen activator (tPA) leader sequence. After vaccination, this spike protein is produced, promoting the immune system to attack the coronavirus if it later infects the body [@OxfordAstraZenecaCOVID192021].  


`I look at this astounding achievement as pure magic`.


Today was the day I got the 1^st^ dose of COVID vaccine at the Amala Institute of Medical Sciences Vaccination center.


>As I walked to the facility, I was filled with excitement and anxiety. The weight of all these months — staying away from loved ones, taking care of patients, conducting online and offline classes, carrying out covid duties, coupled with the tension-filled job of trying to keep me and my loved ones safe — everything surfaced in me. I wondered, how would I react to the vaccine?

From the moment I got in, to the moment I walked away, I was impressed by the efficiency, the courtesy, the enthusiasm, and the professionalism of the Amala staff assigned to this task. Each step along the way was smooth and well-coordinated, which allowed me to relax and enjoy the experience. The watchman enthusiastically helped me to take some photographs in front of the vaccination center.

I could not have asked for a better experience of getting vaccinated. Hats off to the Community medicine department (especially **Dr Jose Vincent**), `Amala Management` and the `Health department` for being so well-organized and professional. We have much to be proud of.

In the end, I felt a flood of relief and gratitude that vaccines are becoming available less than a year after we recognized there was a novel coronavirus. I thankfully remember the unknown minds and hands behind this incredible feat. 

Bottom-line: **Science rocks and Scientists are rockstars**

### References 
